load("@rules_cc//cc:defs.bzl", "cc_binary")
load("@rules_foreign_cc//foreign_cc:defs.bzl", "configure_make")
load("@emsdk//emscripten_toolchain:wasm_rules.bzl", "wasm_cc_binary")

COMMON_FLAGS = "-s USE_PTHREADS=1 -O3"
LDFLAGS_COMMON = "-s USE_PTHREADS=1 -O3 -s INITIAL_MEMORY=33554432"

configure_make(
    name = "libvpx",
    configure_options = [
        "--target=generic-gnu",
        "--disable-examples",
        "--disable-unit-tests",
        "--disable-install-bins",
        "--disable-tools",
        "--disable-docs",
        "--enable-pic",
    ],
    lib_source = "@libvpx_source//:all_srcs",
    out_static_libs = ["libvpx.a"],
)

configure_make(
    name = "libopus",
    autogen = True,
    configure_in_place = True,
    configure_options = [
        "--host=i686-none",
        "--enable-static",
        "--disable-shared",
        "--disable-asm",
        "--disable-rtcd",
        "--disable-intrinsics",
        "--disable-doc",
        "--disable-extra-programs",
    ],
    lib_source = "@libopus_source//:all_srcs",
    out_static_libs = ["libopus.a"],
)

configure_make(
    name = "lame",
    configure_options = [
        "--host=i686-gnu",
        "--enable-static",
        "--disable-frontend",
    ],
    lib_source = "@lame_source//:all_srcs",
    out_static_libs = ["libmp3lame.a"],
)

configure_make(
    name = "libwebp",
    autogen = True,
    configure_in_place = True,
    configure_options = [
        "--disable-shared",
    ],
    lib_source = "@libwebp_source//:all_srcs",
    out_static_libs = ["libwebp.a"],
)

configure_make(
    name = "ffmpeg",
    configure_options = [
        "--target-os=none",
        "--arch=x86_32",
        "--enable-cross-compile",
        "--disable-debug",
        "--disable-x86asm",
        "--disable-inline-asm",
        "--disable-stripping",
        "--disable-programs",
        "--disable-doc",
        "--disable-all",
        "--enable-avcodec",
        "--enable-avformat",
        "--enable-avfilter",
        "--enable-avdevice",
        "--enable-avutil",
        "--enable-swresample",
        "--enable-postproc",
        "--enable-swscale",
        "--enable-protocol=file",
        "--enable-decoder=aac,pcm_s16le,mp3",
        "--enable-demuxer=dash,mov,matroska,mp3,webm",
        "--enable-muxer=dash,mp4,webm",
        "--disable-gpl",
        "--enable-libvpx",
        "--enable-libopus",
        "--enable-libmp3lame",
        "--enable-libwebp",
        "--extra-cflags='%s'" % COMMON_FLAGS,
        "--extra-cxxflags='%s'" % COMMON_FLAGS,
        "--extra-ldflags='%s'" % LDFLAGS_COMMON,
        "--nm='llvm-nm -g'",
        "--ar=emar",
        "--as=llvm-as",
        "--ranlib=emranlib",
        "--cc=emcc",
        "--cxx=em++",
        "--objcc=emcc",
        "--dep-cc=emcc",
    ],
    env = {
        "CFLAGS": COMMON_FLAGS,
        "CXXFLAGS": COMMON_FLAGS,
        "LDFLAGS": LDFLAGS_COMMON,
    },
    lib_source = "@ffmpeg_source//:all_srcs",
    out_static_libs = [
        "libavcodec.a", "libavformat.a", "libavfilter.a", "libavdevice.a",
        "libswresample.a", "libswscale.a", "libavutil.a", "libpostproc.a"
    ],
    deps = [":libvpx", ":libopus", ":lame", ":libwebp"],
)

cc_binary(
    name = "ikaria_wasm_raw",
    srcs = ["src/dash.cpp"],
    copts = [COMMON_FLAGS],
    linkopts = [
        "-O3",
        "--bind",
        "-sEXPORTED_RUNTIME_METHODS=['FS','cwrap','ccall','getValue','setValue','writeAsciiToMemory']",
        "-sINITIAL_MEMORY=268435456",
        "-sEXPORT_ES6=1",
        "--emit-tsd=ikaria-wasm.d.ts",
        "-sWASMFS",
        "-sFORCE_FILESYSTEM",
        "-sASSERTIONS",
        "-sPTHREAD_POOL_SIZE=navigator.hardwareConcurrency",
        "-pthread",
    ],
    deps = [":ffmpeg"],
)

wasm_cc_binary(
    name = "ikaria_wasm",
    cc_target = ":ikaria_wasm_raw",
    outputs = [
        "ikaria-wasm.js",
        "ikaria-wasm.wasm",
    ],
)
