module(
    name = "ikaria",
    version = "1.0.0",
)

bazel_dep(name = "platforms", version = "1.0.0")
bazel_dep(name = "rules_cc", version = "0.1.1")
bazel_dep(name = "rules_foreign_cc", version = "0.15.1")
bazel_dep(name = "rules_license", version = "1.0.0")
bazel_dep(name = "emsdk", version = "4.0.17")
bazel_dep(name = "googletest", version = "1.17.0")

git_override(
    module_name = "emsdk",
    remote = "https://github.com/emscripten-core/emsdk.git",
    strip_prefix = "bazel",
    tag = "4.0.17",
)

emscripten_deps = use_extension(
    "@emsdk//:emscripten_deps.bzl",
    "emscripten_deps",
)
emscripten_deps.config(version = "4.0.17")

register_toolchains("@rules_foreign_cc//toolchains:all")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "ffmpeg_source",
    build_file_content = 'filegroup(name = "all_srcs", srcs = glob(["**"]), visibility = ["//visibility:public"])',
    strip_prefix = "ffmpeg-7.1.1",
    urls = ["https://ffmpeg.org/releases/ffmpeg-7.1.1.tar.gz"],
)

http_archive(
    name = "libxml2_source",
    build_file_content = 'filegroup(name = "all_srcs", srcs = glob(["**"]), visibility = ["//visibility:public"])',
    strip_prefix = "libxml2-2.15.1",
    urls = ["https://download.gnome.org/sources/libxml2/2.15/libxml2-2.15.1.tar.xz"],
)

http_archive(
    name = "boringssl_source",
    strip_prefix = "boringssl-main",
    urls = ["https://github.com/google/boringssl/archive/refs/heads/main.tar.gz"],
)

http_archive(
    name = "curl_source",
    build_file_content = 'filegroup(name = "all_srcs", srcs = glob(["**"]), visibility = ["//visibility:public"])',
    strip_prefix = "curl-8.17.0",
    urls = ["https://github.com/curl/curl/releases/download/curl-8_17_0/curl-8.17.0.tar.gz"],
)

bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    remote = "https://github.com/hedronvision/bazel-compile-commands-extractor.git",
    commit = "abb61a688167623088f8768cc9264798df6a9d10",
)
