version: '3'

env:
  PREFIX: /opt/ffmpeg
  MAKEFLAGS: -j4
  LIBVPX_VERSION: 1.15.1
  OPUS_VERSION: 1.5.2
  LAME_VERSION: "3.100"
  FFMPEG_VERSION: 7.1.1
  CFLAGS: -s USE_PTHREADS=1 -O3 -I{{.PREFIX}}/include
  LDFLAGS: -s USE_PTHREADS=1 -O3 -I{{.PREFIX}}/include -L{{.PREFIX}}/lib -s INITIAL_MEMORY=33554432

tasks:
  build-libvpx:
    dir: /tmp
    cmds:
      - git clone https://chromium.googlesource.com/webm/libvpx
      - cd /tmp/libvpx && git checkout v{{.LIBVPX_VERSION}}
      - cd /tmp/libvpx && emconfigure ./configure --target=generic-gnu --prefix={{.PREFIX}} --disable-examples --disable-unit-tests --disable-install-bins --disable-tools --disable-docs --enable-pic
      - cd /tmp/libvpx && emmake make && emmake make install

  build-opus:
    dir: /tmp
    cmds:
      - git clone https://github.com/xiph/opus
      - cd /tmp/opus && git checkout v{{.OPUS_VERSION}}
      - cd /tmp/opus && emconfigure ./autogen.sh
      - cd /tmp/opus && emconfigure ./configure --prefix={{.PREFIX}} --host=i686-none --enable-static --disable-shared --disable-asm --disable-rtcd --disable-intrinsics --disable-doc --disable-extra-programs
      - cd /tmp/opus && emmake make && emmake make install

  build-lame:
    dir: /tmp
    cmds:
      - wget -O lame-{{.LAME_VERSION}}.tar.gz https://sourceforge.net/projects/lame/files/lame/{{.LAME_VERSION}}/lame-{{.LAME_VERSION}}.tar.gz/download
      - tar zxf lame-{{.LAME_VERSION}}.tar.gz
      - cd /tmp/lame-{{.LAME_VERSION}} && emconfigure ./configure --prefix={{.PREFIX}} --host=i686-gnu --enable-static --disable-frontend
      - cd /tmp/lame-{{.LAME_VERSION}} && emmake make && emmake make install

  download-ffmpeg:
    dir: /tmp
    cmds:
      - wget https://ffmpeg.org/releases/ffmpeg-{{.FFMPEG_VERSION}}.tar.gz
      - tar zxf ffmpeg-{{.FFMPEG_VERSION}}.tar.gz && rm ffmpeg-{{.FFMPEG_VERSION}}.tar.gz

  build-ffmpeg:
    cmds:
      - |
        cd /tmp/ffmpeg-{{.FFMPEG_VERSION}} && emconfigure ./configure \
        --prefix={{.PREFIX}} \
        --target-os=none \
        --arch=x86_32 \
        --enable-cross-compile \
        --disable-debug \
        --disable-x86asm \
        --disable-inline-asm \
        --disable-stripping \
        --disable-programs \
        --disable-doc \
        --disable-all \
        --enable-avcodec \
        --enable-avformat \
        --enable-avfilter \
        --enable-avdevice \
        --enable-avutil \
        --enable-swresample \
        --enable-postproc \
        --enable-swscale \
        --enable-protocol=file \
        --enable-decoder=aac,pcm_s16le,mp3 \
        --enable-demuxer=mov,matroska,mp3,webm \
        --enable-muxer=mp4,webm \
        --disable-gpl \
        --enable-libvpx \
        --enable-libopus \
        --enable-libmp3lame \
        --extra-cflags="{{.CFLAGS}}" \
        --extra-cxxflags="{{.CFLAGS}}" \
        --extra-ldflags="{{.LDFLAGS}}" \
        --nm="llvm-nm -g" \
        --ar=emar \
        --as=llvm-as \
        --ranlib=emranlib \
        --cc=emcc \
        --cxx=em++ \
        --objcc=emcc \
        --dep-cc=emcc
      - cd /tmp/ffmpeg-{{.FFMPEG_VERSION}} && emmake make -j4 && emmake make install    
  
  build-deps:
    deps: [build-libvpx, build-opus, build-lame, download-ffmpeg] 
    cmds:
      - task: build-ffmpeg
  
  clean:
    cmds:
      - rm -f js/src/ikaria-wasm.js
      - rm -f js/src/ikaria-wasm.wasm
  
  build:
    cmds:
      - task: clean
      - |
        emcc --bind \
        -O3 \
        -L{{.PREFIX}}/lib \
        -I{{.PREFIX}}/include/ \
        -s EXPORTED_RUNTIME_METHODS="[FS, cwrap, ccall, getValue, setValue, writeAsciiToMemory]" \
        -s INITIAL_MEMORY=268435456 \
        -s EXPORT_ES6=1 --emit-tsd ikaria-wasm.d.ts \
        -lavcodec -lavformat -lavfilter -lavdevice -lswresample -lswscale -lavutil -lm -lnodefs.js -lidbfs.js -lworkerfs.js \
        -pthread \
        -o js/src/ikaria-wasm.js \
        src/ikaria.cpp



