name: Publish to NPM
permissions: {}

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          echo "DOCKER_COMPOSE_SRC_VOLUME_DIR=./" > .env
          docker compose run ikaria task build

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        working-directory: js
        run: npm install -g pnpm
      
      - name: Install dependencies
        working-directory: js
        run: pnpm install
        

      - name: Build package
        working-directory: js
        run: pnpm build

      - name: Publish to NPM
        working-directory: js
        run: pnpm publish --no-git-checks --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 
